### ISSUE TITLE
Mechanism for setting Accept-Language header

### ISSUE THREAD

**Issue by dakur** [DobryProgramator/idoklad-api-php-client#13]
There are scenarios when you need to set `Accept-Language` header in order to force correct language setting of all pieces in the process so it should be configurable somehow.

**Real world scenarios**

- sending an e-mail with tax document (`Mails/IssuedTaxDocument/Send`), report language is set to Czech
  - current result: the PDF is in Czech, but the e-mail itself is in English
- using `IssuedDocumentPayments` endpoint with `CreateIssuedTaxDocument` set to `true`
  - current result: it generate items in English

Note that I consulted this with iDoklad support and setting `Accept-Language` was their advice. It's actually listed down in [FAQ](https://api.idoklad.cz/Help/v3/cs/#api-_footer), but there only print documents are mentioned there, not e-mails or auto-generated items which it works well for as well.

**Comment by dakur** [comment]
I would pass it as a second parameter to client's `sendRequest()`/`makeRequest()` method with default to null. Is this ok for you? I can prepare a pull request.

**Comment by Holicz** [comment]
What about:

- creating class property, which would be passed to constructor
- new nullable parameter in sendRequest which would override the class property

This way you could set Accept-Language application wise and override it if your use-case needs it. Also it would make it more convenient when integrating with frameworks (e.g. registering the iDokladApiClient as a Symfony service). 

It would be helpful if you could prepare a MR, thanks!

**Comment by dakur** [comment]
Ok, I've create a PR.

**Comment by Holicz** [comment]
Thank you
